-- ============================================================================
-- Generated by scripts/seed-people.mjs — do not edit by hand.
--
-- Regenerate with:
--   node node_modules/tsx/dist/cli.mjs scripts/seed-people.mjs
--
-- Idempotent: safe to re-run against an existing database. Requires
-- 0001_init.sql to have been applied first.
--
-- Source: the roster mirrored from https://bist.edu.bd (snapshot 30 Sep 2026).
-- 39 people hold 47 roles between them.
--
-- The education / experience / publications / awards / memberships / research_areas
-- / identity_links tables are intentionally left empty: the official roster
-- publishes none of those fields, and this project does not invent profile data.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Units
-- ---------------------------------------------------------------------------
insert into public.units (code, name_en, name_bn, kind, display_order) values
  ('CSE', 'B.Sc. (Hons.) in Computer Science & Engineering', 'বি.এসসি (অনার্স) ইন কম্পিউটার সায়েন্স অ্যান্ড ইঞ্জিনিয়ারিং (সিএসই)', 'department', 0),
  ('TST', 'B.Sc. (Hons.) in Textile Science & Technology', 'বি.এসসি (অনার্স) ইন টেক্সটাইল সায়েন্স অ্যান্ড টেকনোলজি (টিএসটি)', 'department', 1),
  ('AMT', 'B.Sc. (Hons.) in Apparel Manufacture & Technology', 'বি.এসসি (অনার্স) ইন অ্যাপারেল ম্যানুফ্যাকচার অ্যান্ড টেকনোলজি (এএমটি)', 'department', 2),
  ('FDT', 'B.Sc. (Hons.) in Fashion Design & Technology', 'বি.এসসি (অনার্স) ইন ফ্যাশন ডিজাইন অ্যান্ড টেকনোলজি (এফডিটি)', 'department', 3),
  ('BBA', 'Bachelor of Business Administration (Professional BBA)', 'ব্যাচেলর অব বিজনেস অ্যাডমিনিস্ট্রেশন (প্রফেশনাল বিবিএ)', 'department', 4),
  ('ADMIN', 'Administration', 'প্রশাসন', 'department', 99),
  ('academy-admin-and-hr', 'Academy, Admin & HR', 'একাডেমি, প্রশাসন ও এইচআর', 'office', 2),
  ('office-of-the-registrar', 'Office of the Registrar', 'রেজিস্ট্রার শাখা', 'office', 1),
  ('computer-science-and-engineering-cse', 'Computer Science & Engineering (CSE)', 'কম্পিউটার সায়েন্স অ্যান্ড ইঞ্জিনিয়ারিং (CSE)', 'office', 6),
  ('computer-technology', 'Computer Technology', 'কম্পিউটার টেকনোলজি', 'office', 5),
  ('project', 'Project', 'প্রকল্প', 'office', 8)
on conflict (code) do update set
  name_en = excluded.name_en,
  name_bn = excluded.name_bn,
  kind = excluded.kind,
  display_order = excluded.display_order;

-- ---------------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------------
insert into public.people (slug, name_en, name_bn, qualifications, photo_url, email, profile_url, cv_url, short_bio_en, short_bio_bn, full_bio_en, full_bio_bn, phone, room_no, is_published) values
  ('prof-nurul-amin', 'Prof. Nurul Amin', 'প্রফেসর নুরুল আমিন', 'M.Sc In Mathematics, Diploma In Education', './images/teachers/prof-nurul-amin.jpeg', 'namin1199011949@gmail.com', 'https://bist.edu.bd/teacher-details/prof-nurul-amin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-robiul-islam', 'MD Robiul Islam', 'মোঃ রবিউল ইসলাম', 'M.Sc Engg. in Electrical Engineering, Hohai University, Nanjing, China. M.Sc in ECE, Islamic University, Kushtia. B.Sc in ECE, National University, Gazipur.', './images/teachers/md-robiul-islam.jpg', 'robiul.islamapece1691@gmail.com', 'https://bist.edu.bd/teacher-details/md-robiul-islam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('nasima-akter-roqsana', 'Nasima Akter Roqsana', 'নাসিমা আক্তার রোকসানা', 'B.Sc In Fashion Design', './images/teachers/nasima-akter-roqsana.jpg', 'roqsanaakter@gmail.com', 'https://bist.edu.bd/teacher-details/nasima-akter-roqsana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-aminur-islam', 'MD. Aminur Islam', 'মোঃ আমিনুর ইসলাম', 'M.Sc. & B.Sc. in Textile Engineering (DUET)', './images/teachers/md-aminur-islam.jpg', 'duetexaminur@gmail.com', 'https://bist.edu.bd/teacher-details/md-aminur-islam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('esrat-jahan-nipa', 'Esrat Jahan Nipa', 'এছরাত জাহান নিপা', 'BBA & MBA in Management at National University, Gazipur', './images/teachers/esrat-jahan-nipa.jpg', 'esratjahannipa113@gmail.com', 'https://bist.edu.bd/teacher-details/esrat-jahan-nipa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-shohidul-islam', 'Engr. MD. Shohidul Islam', 'প্রকৌশলী মোঃ শহীদুল ইসলাম', 'PGD in Advance Computer Technology & B.Sc in CSE', './images/teachers/md-shohidul-islam.jpg', 'registerinfo.bist@gmail.com', 'https://bist.edu.bd/teacher-details/md-shohidul-islam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('nowkisa-tabassum-raiyan', 'Nowkisa Tabassum Raiyan', 'নওকিসা তাবাসসুম রাইয়ান', 'MBA in Product & Fashion Merchandising', './images/teachers/nowkisa-tabassum-raiyan.jpeg', 'nowkisa1104@gmail.com', 'https://bist.edu.bd/teacher-details/nowkisa-tabassum-raiyan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('jahir-ahmed-rifat', 'Jahir Ahmed Rifat', 'জহির আহমেদ রিফাত', 'MBA, BBA in Finance and Banking from Jatiya Kabi Kazi Nazrul Islam University', './images/teachers/jahir-ahmed-rifat.jpeg', 'jahirahmedrifat.fnb@gmail.com', 'https://bist.edu.bd/teacher-details/jahir-ahmed-rifat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('m-m-abdul-kader', 'M. M. Abdul Kader', 'এম. এম. আব্দুল কাদের', 'BSc in Textile Engineering (Apparel Manufacturing) from DUET', './images/teachers/m-m-abdul-kader.jpg', 'mm.abdul610@gmail.com', 'https://bist.edu.bd/teacher-details/m-m-abdul-kader', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('shabnom-mustary', 'Shabnom Mustary', 'শাবনম মুস্তারি', 'Ph.D (On going), DUET; M.Sc in CSE, Friendship University of Russia', './images/teachers/shabnom-mustary.jpg', 'shobnom93717@gmail.com', 'https://bist.edu.bd/teacher-details/shabnom-mustary', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('mohammad-naderuzzaman', 'MD Naderuzzaman', 'মোঃ নাদেরুজ্জামান', 'Ph.D (On going), DUET; M.Sc in CSE, DUET', './images/teachers/mohammad-naderuzzaman.jpg', 'nader_u@yahoo.com', 'https://bist.edu.bd/teacher-details/mohammad-naderuzzaman', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('rahat-kanon', 'Rahat Kanon', 'রাহাত কানন', 'MBA major in Finance & Banking', './images/teachers/rahat-kanon.jpeg', 'meraj.rahat001@gmail.com', 'https://bist.edu.bd/teacher-details/rahat-kanon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('hasna-majury-tandra', 'Hasna Majury Tandra', 'হাসনা মজুরী তন্দ্রা', 'B.Sc & M.Sc in Mathematics from Shahjalal University of Science and Technology', './images/teachers/hasna-majury-tandra.jpg', 'majurytandra@gmail.com', 'https://bist.edu.bd/teacher-details/hasna-majury-tandra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('abu-saeid', 'Abu Saeid', 'আবু সাঈদ', 'M.Sc. in CSE (On going), DUET & B.Sc. (Engg) in CSE, DUET', './images/teachers/abu-saeid.jpg', 'saeid.duet@gmail.com', 'https://bist.edu.bd/teacher-details/abu-saeid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('imran-hossen', 'Imran Hossen', 'ইমরান হোসেন', 'B.Sc.(Engg) in CSE from DUET', './images/teachers/imran-hossen.jpg', 'imranduet22@gmail.com', 'https://bist.edu.bd/teacher-details/imran-hossen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('israt-jahan-esha', 'Israt Jahan Esha', 'ইসরাত জাহান ঈশা', 'MSS & BSS in Economics from Mawlana Bhashani Science & Technology University', './images/teachers/israt-jahan-esha.jpeg', 'isratesha618746@gmail.com', 'https://bist.edu.bd/teacher-details/israt-jahan-esha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('niger-sultana', 'Niger Sultana', 'নাইজার সুলতানা', 'Masters of Business Administration (MBA)', './images/teachers/niger-sultana.webp', 'nigershelysultana1984@gmail.com', 'https://bist.edu.bd/teacher-details/niger-sultana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('salma-khatun', 'Salma Khatun', 'সালমা খাতুন', NULL, './images/teachers/salma-khatun.webp', 'salmakhatun4514@gmail.com', 'https://bist.edu.bd/teacher-details/salma-khatun', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('ak-azad', 'AK. Azad', 'এ.কে. আজাদ', 'CFA, Pre-BFA, BFA (Hon''s), MFA', './images/teachers/ak-azad.jpg', 'ak.azad198421@gmail.com', 'https://bist.edu.bd/teacher-details/aK-azad', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('afra-ibnath-tithy', 'Afra Ibnath Tithy', 'আফরা ইবনাত তিথি', 'B.Sc.(Engg) in EEE from RUET', './images/teachers/afra-ibnath-tithy.jpeg', 'afratithy5244@gmail.com', 'https://bist.edu.bd/teacher-details/afra-ibnath-tithy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-monjurul-islam-pranto', 'Md. Monjurul Islam Pranto', 'মোঃ মনজুরুল ইসলাম প্রান্ত', 'M.Sc (Ongoing) & B.Sc. in Textile Engineering at Dhaka University of Engineering & Technology (DUET), Gazipur', './images/teachers/md-monjurul-islam-pranto.jpg', 'pranto.duet.te@gmail.com', 'https://bist.edu.bd/teacher-details/md-monjurul-islam-pranto', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('mr-uzzal-roy', 'Uzzal Roy', 'উজ্জ্বল রায়', 'M.Sc. (Ongoing) & B.Sc. in Textile Engineering (DUET)', './images/teachers/mr-uzzal-roy.jpg', 'uroy6490@gmail.com', 'https://bist.edu.bd/teacher-details/mr-uzzal-roy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-saukat-hossain', 'Md. Saukat Hossain', 'মোঃ সৌকত হোসেন', 'Bachelor & Masters of Social Science (HSTU)', './images/teachers/md-saukat-hossain.jpg', 'saukathstu@gmail.com', 'https://bist.edu.bd/teacher-details/md-saukat-hossain', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('azizul-islam', 'Azizul Islam', 'আজিজুল ইসলাম', 'B.Sc in CSE (Bangladesh University)', './images/teachers/azizul-islam.webp', 'cseazizul@gmail.com', 'https://bist.edu.bd/teacher-details/azizul-islam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-shimuljoy-sobuj', 'Md. ShimulJoy Sobuj', 'মোঃ শিমুলজয় সবুজ', 'Advance Computer Technology, BSS (Hon''s), Diploma in DGT', './images/teachers/md-shimuljoy-sobuj.jpg', 'bistshimul@gmail.com', 'https://bist.edu.bd/teacher-details/md-shimulJoy-sobuj', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('alamgir-hossain', 'Alamgir Hossain', 'আলমগীর হোসেন', 'B.Sc In CSE (Southeast University)', './images/teachers/alamgir-hossain.webp', 'smalamgirhossain9@gmail.com', 'https://bist.edu.bd/teacher-details/alamgir-hossain', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('shalah-uddin-perbhez-shakil', 'Shalah Uddin Perbhez Shakil', 'শালাহ উদ্দিন পরভেজ শাকিল', 'M.Sc. in CSE', './images/teachers/shalah-uddin-perbhez-shakil.jpg', 'shakilcse24@gmail.com', 'https://bist.edu.bd/teacher-details/shalah-uddin-perbhez-shakil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-yousuf-hossain', 'Md. Yousuf Hossain', 'মোঃ ইউসুফ হোসেন', 'Economics (BSS & MSS)', './images/teachers/md-yousuf-hossain.jpeg', 'yousufshuvo169@gmail.com', 'https://bist.edu.bd/teacher-details/md-yousuf-hossain', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('sumiayia-hashem', 'Sumiayia Hashem', 'সুমাইয়া হাশেম', 'MSc in Fashion Design from BUFT & BSc in Textile Engineering (Major in Apparel Manufacturing) from AUST', './images/teachers/sumiayia-hashem.jpg', 'sumaiya.hashem360@gmail.com', 'https://bist.edu.bd/teacher-details/sumiayia-hashem', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-azizur-rahman', 'Md. Azizur Rahman', 'মোঃ আজিজুর রহমান', 'BSc In Textile Engineering', './images/teachers/md-azizur-rahman.jpg', 'eng.arsumon@gmail.com', 'https://bist.edu.bd/teacher-details/md-azizur-rahman', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('g-m-rafi-ahamed', 'G.M. Rafi Ahamed', 'জি.এম. রফি আহমেদ', 'M.Sc in Physics', './images/teachers/g-m-rafi-ahamed.jpg', 'gmrafiku43@gmail.com', 'https://bist.edu.bd/teacher-details/g-m-rafi-ahamed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-salauddin', 'MD Salauddin', 'মোঃ সালাউদ্দিন', 'B.Sc in Textile', './images/teachers/md-salauddin.jpeg', 'salauddindorjoy69@gmail.com', 'https://bist.edu.bd/teacher-details/md-salauddin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('shariful-haque', 'Shariful Haque', 'শরিফুল হক', 'B.Sc. in EEE', './images/teachers/shariful-haque.jpg', 'sharifulhaqueeee@gmail.com', 'https://bist.edu.bd/teacher-details/shariful-haque', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('anamul-haque', 'Anamul Haque', 'আনামুল হক', 'M.Sc in CSE (Running) & B.Sc. in CSE', './images/teachers/anamul-haque.jpeg', 'anamulhasan2814@gmail.com', 'https://bist.edu.bd/teacher-details/anamul-haque', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-firoz-hossain', 'Md. Firoz Hossain', 'মোঃ ফিরোজ হোসেন', 'MSc in Textile Engineering (DUET); BSc in Textile Engineering (DUET)', './images/teachers/md-firoz-hossain.jpg', 'firozhossain334@gmail.com', 'https://bist.edu.bd/teacher-details/md-firoz-hossain', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('abu-asad', 'Abu Asad', 'আবু আসাদ', 'B.Sc. in Textile Engineering', './images/teachers/abu-asad.jpg', 'mdasad497@gmail.com', 'https://bist.edu.bd/teacher-details/abu-asad', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-ismail-hossain', 'Md Ismail Hossain', 'মোঃ ইসমাইল হোসেন', 'MA', './images/person-placeholder.png', 'ismaillmaster@gmail.com', 'https://bist.edu.bd/teacher-details/md-ismail-hossain', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('abu-bakkar-siddik', 'Abu Bakkar Siddik', 'আবু বক্কর সিদ্দিক', 'B.Sc in AMT', './images/teachers/abu-bakkar-siddik.jpg', 'abubakkarsiddik@gmail.com', 'https://bist.edu.bd/teacher-details/abu-bakkar-siddik', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('md-manirul-islam', 'Md. Manirul Islam', 'মোঃ মনিরুল ইসলাম', 'BSc in Textile Engineering (University of Dhaka); MBA in Apparel Merchandising (National University)', './images/teachers/md-manirul-slam.webp', 'manirdu92@gmail.com', 'https://bist.edu.bd/teacher-details/md-manirul-slam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_bn = excluded.name_bn,
  qualifications = excluded.qualifications,
  photo_url = excluded.photo_url,
  email = excluded.email,
  profile_url = excluded.profile_url,
  cv_url = excluded.cv_url,
  short_bio_en = excluded.short_bio_en,
  short_bio_bn = excluded.short_bio_bn,
  full_bio_en = excluded.full_bio_en,
  full_bio_bn = excluded.full_bio_bn,
  phone = excluded.phone,
  room_no = excluded.room_no,
  is_published = excluded.is_published;

-- ---------------------------------------------------------------------------
-- Roles
--
-- person_id is resolved from the slug, so this can run whether or not the
-- people insert above created the rows.
-- ---------------------------------------------------------------------------
insert into public.person_roles (
  person_id, unit_code, role, designation_en, designation_bn,
  responsibilities_en, responsibilities_bn, employment_type,
  display_order, is_primary, legacy_id
)
select
  p.id, v.unit_code, v.role, v.designation_en, v.designation_bn,
  v.responsibilities_en, v.responsibilities_bn, v.employment_type,
  v.display_order, v.is_primary, v.legacy_id
from (values
  ('prof-nurul-amin', 'ADMIN', 'faculty', 'Vice-Principal', 'উপাধ্যক্ষ', NULL, NULL, 'Full-Time', 0, true, 'prof-nurul-amin'),
  ('prof-nurul-amin', 'academy-admin-and-hr', 'officer', 'Vice-Principal', 'উপাধ্যক্ষ', NULL, NULL, NULL, 2, false, 'off-vice-principal'),
  ('md-robiul-islam', 'CSE', 'faculty', 'Asst. Professor & Head of Department', 'সহকারী অধ্যাপক ও বিভাগীয় প্রধান', NULL, NULL, 'Full-Time', 0, true, 'md-robiul-islam'),
  ('nasima-akter-roqsana', 'FDT', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Full-Time', 0, true, 'nasima-akter-roqsana'),
  ('md-aminur-islam', 'AMT', 'faculty', 'Acting Coordinator', 'ভারপ্রাপ্ত সমন্বয়ক', NULL, NULL, 'Full-Time', 0, true, 'md-aminur-islam'),
  ('esrat-jahan-nipa', 'BBA', 'faculty', 'Assistant Professor & Coordinator', 'সহকারী অধ্যাপক ও সমন্বয়ক', NULL, NULL, 'Full-Time', 0, true, 'esrat-jahan-nipa'),
  ('md-shohidul-islam', 'ADMIN', 'faculty', 'Registrar', 'রেজিস্ট্রার', NULL, NULL, 'Full-Time', 0, true, 'md-shohidul-islam'),
  ('md-shohidul-islam', 'office-of-the-registrar', 'officer', 'Registrar', 'রেজিস্ট্রার', NULL, NULL, NULL, 1, false, 'off-registrar'),
  ('nowkisa-tabassum-raiyan', 'FDT', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Full-Time', 0, true, 'nowkisa-tabassum-raiyan'),
  ('jahir-ahmed-rifat', 'BBA', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'jahir-ahmed-rifat'),
  ('m-m-abdul-kader', 'AMT', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'm-m-abdul-kader'),
  ('shabnom-mustary', 'CSE', 'faculty', 'Assistant Professor & Coordinator', 'সহকারী অধ্যাপক ও সমন্বয়ক', NULL, NULL, 'Full-Time', 0, true, 'shabnom-mustary'),
  ('mohammad-naderuzzaman', 'CSE', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Full-Time', 0, true, 'mohammad-naderuzzaman'),
  ('rahat-kanon', 'BBA', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Part-Time', 0, true, 'rahat-kanon'),
  ('hasna-majury-tandra', 'AMT', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'hasna-majury-tandra'),
  ('abu-saeid', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'abu-saeid'),
  ('imran-hossen', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'imran-hossen'),
  ('israt-jahan-esha', 'BBA', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'israt-jahan-esha'),
  ('niger-sultana', 'BBA', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Part-Time', 0, true, 'niger-sultana'),
  ('salma-khatun', 'FDT', 'faculty', 'Senior Lecturer', 'সিনিয়র প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'salma-khatun'),
  ('ak-azad', 'FDT', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Full-Time', 0, true, 'ak-azad'),
  ('afra-ibnath-tithy', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'afra-ibnath-tithy'),
  ('md-monjurul-islam-pranto', 'AMT', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'md-monjurul-islam-pranto'),
  ('mr-uzzal-roy', 'TST', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'mr-uzzal-roy'),
  ('md-saukat-hossain', 'BBA', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'md-saukat-hossain'),
  ('azizul-islam', 'CSE', 'faculty', 'Software Developer', 'সফটওয়্যার ডেভেলপার', NULL, NULL, 'Full-Time', 0, true, 'azizul-islam'),
  ('azizul-islam', 'computer-science-and-engineering-cse', 'officer', 'Software Developer', 'সফটওয়্যার ডেভেলপার', NULL, NULL, NULL, 6, false, 'off-software-developer'),
  ('md-shimuljoy-sobuj', 'ADMIN', 'faculty', 'Graphics Designer', 'গ্রাফিক্স ডিজাইনার', NULL, NULL, 'Full-Time', 0, true, 'md-shimuljoy-sobuj'),
  ('md-shimuljoy-sobuj', 'computer-technology', 'officer', 'Graphics Designer', 'গ্রাফিক্স ডিজাইনার', NULL, NULL, NULL, 5, false, 'off-graphics'),
  ('alamgir-hossain', 'CSE', 'faculty', 'Jr. Software Developer', 'জুনিয়র সফটওয়্যার ডেভেলপার', NULL, NULL, 'Part-Time', 0, true, 'alamgir-hossain'),
  ('alamgir-hossain', 'computer-science-and-engineering-cse', 'officer', 'Jr. Software Developer', 'জুনিয়র সফটওয়্যার ডেভেলপার', NULL, NULL, NULL, 7, false, 'off-jr-software-developer'),
  ('shalah-uddin-perbhez-shakil', 'CSE', 'faculty', 'Senior Lecturer', 'সিনিয়র প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'shalah-uddin-perbhez-shakil'),
  ('md-yousuf-hossain', 'BBA', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Part-Time', 0, true, 'md-yousuf-hossain'),
  ('sumiayia-hashem', 'FDT', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'sumiayia-hashem'),
  ('md-azizur-rahman', 'ADMIN', 'faculty', 'Admission Officer', 'ভর্তি কর্মকর্তা', NULL, NULL, 'Full-Time', 0, true, 'md-azizur-rahman'),
  ('md-azizur-rahman', 'academy-admin-and-hr', 'officer', 'Admission Officer', 'ভর্তি কর্মকর্তা', NULL, NULL, NULL, 3, false, 'off-admission'),
  ('g-m-rafi-ahamed', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'g-m-rafi-ahamed'),
  ('md-salauddin', 'ADMIN', 'faculty', 'Acting Coordinator', 'ভারপ্রাপ্ত সমন্বয়ক', NULL, NULL, 'Full-Time', 0, true, 'md-salauddin'),
  ('md-salauddin', 'project', 'officer', 'Acting Coordinator (Project)', 'ভারপ্রাপ্ত সমন্বয়ক (প্রকল্প)', NULL, NULL, NULL, 8, false, 'off-project-coordinator'),
  ('shariful-haque', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'shariful-haque'),
  ('anamul-haque', 'CSE', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Part-Time', 0, true, 'anamul-haque'),
  ('md-firoz-hossain', 'TST', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'md-firoz-hossain'),
  ('abu-asad', 'TST', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Full-Time', 0, true, 'abu-asad'),
  ('md-ismail-hossain', 'ADMIN', 'faculty', 'Public Relations Officer', 'জনসংযোগ কর্মকর্তা', NULL, NULL, 'Full-Time', 0, true, 'md-ismail-hossain'),
  ('md-ismail-hossain', 'academy-admin-and-hr', 'officer', 'Public Relations Officer', 'জনসংযোগ কর্মকর্তা', NULL, NULL, NULL, 4, false, 'off-public-relations'),
  ('abu-bakkar-siddik', 'AMT', 'faculty', 'Lecturer', 'প্রভাষক', NULL, NULL, 'Part-Time', 0, true, 'abu-bakkar-siddik'),
  ('md-manirul-islam', 'AMT', 'faculty', 'Assistant Professor', 'সহকারী অধ্যাপক', NULL, NULL, 'Part-Time', 0, true, 'md-manirul-islam')
) as v(
  slug, unit_code, role, designation_en, designation_bn,
  responsibilities_en, responsibilities_bn, employment_type,
  display_order, is_primary, legacy_id
)
join public.people p on p.slug = v.slug
on conflict (person_id, unit_code, role) do update set
  designation_en = excluded.designation_en,
  designation_bn = excluded.designation_bn,
  responsibilities_en = excluded.responsibilities_en,
  responsibilities_bn = excluded.responsibilities_bn,
  employment_type = excluded.employment_type,
  display_order = excluded.display_order,
  is_primary = excluded.is_primary,
  legacy_id = excluded.legacy_id;

-- ---------------------------------------------------------------------------
-- Post-seed sanity check: every person must have at least one role.
-- ---------------------------------------------------------------------------
do $$
declare orphan_count int;
begin
  select count(*) into orphan_count
  from public.people p
  where not exists (select 1 from public.person_roles r where r.person_id = p.id);

  if orphan_count > 0 then
    raise exception '% people were seeded without a role', orphan_count;
  end if;

  raise notice 'Seeded % people and % roles.', 39, 47;
end $$;
