/**
 * Generates `supabase/seed.sql` from the mirrored roster.
 *
 * Run with:
 *   node node_modules/tsx/dist/cli.mjs scripts/seed-people.mjs
 *
 * This is .mjs rather than .cjs because it imports the TypeScript data modules,
 * which plain `node` cannot do — `tsx` supplies the loader.
 *
 * The roster is already unified in `src/data/people.ts` (39 people, each with one
 * or more roles), so this script's job is purely to translate it — no merging
 * happens here. Programme names come from the catalogue so the Bengali unit names
 * are the ones the institute actually publishes rather than a fresh translation.
 */

import fs from 'node:fs';
import { PEOPLE } from '../src/data/people.ts';
import { PROGRAMS } from '../src/data/catalogData.ts';

const OUT = 'supabase/seed.sql';

/** Quote a value for SQL, or emit NULL. */
const lit = (value) => {
  if (value === null || value === undefined || value === '') return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${String(value).replace(/'/g, "''")}'`;
};

const unitRows = [];
const seenUnits = new Set();

const addUnit = (code, nameEn, nameBn, kind, order) => {
  if (!code || seenUnits.has(code)) return;
  seenUnits.add(code);
  unitRows.push({ code, nameEn, nameBn, kind, order });
};

// Departments, named from the programme catalogue (real mirrored titles).
for (const [index, prog] of PROGRAMS.entries()) {
  addUnit(prog.shortTitle, prog.title.en, prog.title.bn, 'department', index);
}

// The administration wing is a roster department but not a degree programme.
addUnit('ADMIN', 'Administration', 'প্রশাসন', 'department', 99);

// Offices, named from the office string published against each officer role.
for (const person of PEOPLE) {
  for (const role of person.roles) {
    if (role.role !== 'officer') continue;
    addUnit(
      role.unitCode,
      role.unitName?.en ?? role.unitCode,
      role.unitName?.bn ?? null,
      'office',
      role.displayOrder
    );
  }
}

// --- people -----------------------------------------------------------------
const peopleValues = PEOPLE.map((p) => {
  const primary = p.roles.find((r) => r.isPrimary) ?? p.roles[0];
  return `  (${[
    lit(p.slug),
    lit(p.name.en),
    lit(p.name.bn),
    lit(p.qualifications),
    lit(p.photo),
    lit(p.email),
    lit(p.profileUrl),
    lit(p.cvUrl),
    lit(p.shortBio?.en),
    lit(p.shortBio?.bn),
    lit(p.fullBio?.en),
    lit(p.fullBio?.bn),
    lit(p.phone),
    lit(p.roomNo),
    lit(true), // is_published — mirrored people are public by default
  ].join(', ')})`;
});

const peopleColumns = [
  'slug',
  'name_en',
  'name_bn',
  'qualifications',
  'photo_url',
  'email',
  'profile_url',
  'cv_url',
  'short_bio_en',
  'short_bio_bn',
  'full_bio_en',
  'full_bio_bn',
  'phone',
  'room_no',
  'is_published',
];

// --- roles ------------------------------------------------------------------
const roleValues = [];
for (const p of PEOPLE) {
  for (const r of p.roles) {
    roleValues.push(
      `  (${[
        lit(p.slug),
        lit(r.unitCode),
        lit(r.role),
        lit(r.designation.en),
        lit(r.designation.bn),
        lit(r.responsibilities?.en),
        lit(r.responsibilities?.bn),
        lit(r.employmentType),
        lit(r.displayOrder),
        lit(Boolean(r.isPrimary)),
        lit(r.legacyId),
      ].join(', ')})`
    );
  }
}

const sql = `-- ============================================================================
-- Generated by scripts/seed-people.mjs — do not edit by hand.
--
-- Regenerate with:
--   node node_modules/tsx/dist/cli.mjs scripts/seed-people.mjs
--
-- Idempotent: safe to re-run against an existing database. Requires
-- 0001_init.sql to have been applied first.
--
-- Source: the roster mirrored from https://bist.edu.bd (snapshot 30 Sep 2026).
-- ${PEOPLE.length} people hold ${roleValues.length} roles between them.
--
-- The education / experience / publications / awards / memberships / research_areas
-- / identity_links tables are intentionally left empty: the official roster
-- publishes none of those fields, and this project does not invent profile data.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Units
-- ---------------------------------------------------------------------------
insert into public.units (code, name_en, name_bn, kind, display_order) values
${unitRows
  .map(
    (u) =>
      `  (${lit(u.code)}, ${lit(u.nameEn)}, ${lit(u.nameBn)}, ${lit(u.kind)}, ${lit(u.order)})`
  )
  .join(',\n')}
on conflict (code) do update set
  name_en = excluded.name_en,
  name_bn = excluded.name_bn,
  kind = excluded.kind,
  display_order = excluded.display_order;

-- ---------------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------------
insert into public.people (${peopleColumns.join(', ')}) values
${peopleValues.join(',\n')}
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_bn = excluded.name_bn,
  qualifications = excluded.qualifications,
  photo_url = excluded.photo_url,
  email = excluded.email,
  profile_url = excluded.profile_url,
  cv_url = excluded.cv_url,
  short_bio_en = excluded.short_bio_en,
  short_bio_bn = excluded.short_bio_bn,
  full_bio_en = excluded.full_bio_en,
  full_bio_bn = excluded.full_bio_bn,
  phone = excluded.phone,
  room_no = excluded.room_no,
  is_published = excluded.is_published;

-- ---------------------------------------------------------------------------
-- Roles
--
-- person_id is resolved from the slug, so this can run whether or not the
-- people insert above created the rows.
-- ---------------------------------------------------------------------------
insert into public.person_roles (
  person_id, unit_code, role, designation_en, designation_bn,
  responsibilities_en, responsibilities_bn, employment_type,
  display_order, is_primary, legacy_id
)
select
  p.id, v.unit_code, v.role, v.designation_en, v.designation_bn,
  v.responsibilities_en, v.responsibilities_bn, v.employment_type,
  v.display_order, v.is_primary, v.legacy_id
from (values
${roleValues.join(',\n')}
) as v(
  slug, unit_code, role, designation_en, designation_bn,
  responsibilities_en, responsibilities_bn, employment_type,
  display_order, is_primary, legacy_id
)
join public.people p on p.slug = v.slug
on conflict (person_id, unit_code, role) do update set
  designation_en = excluded.designation_en,
  designation_bn = excluded.designation_bn,
  responsibilities_en = excluded.responsibilities_en,
  responsibilities_bn = excluded.responsibilities_bn,
  employment_type = excluded.employment_type,
  display_order = excluded.display_order,
  is_primary = excluded.is_primary,
  legacy_id = excluded.legacy_id;

-- ---------------------------------------------------------------------------
-- Post-seed sanity check: every person must have at least one role.
-- ---------------------------------------------------------------------------
do $$
declare orphan_count int;
begin
  select count(*) into orphan_count
  from public.people p
  where not exists (select 1 from public.person_roles r where r.person_id = p.id);

  if orphan_count > 0 then
    raise exception '% people were seeded without a role', orphan_count;
  end if;

  raise notice 'Seeded % people and % roles.', ${PEOPLE.length}, ${roleValues.length};
end $$;
`;

fs.mkdirSync('supabase', { recursive: true });
fs.writeFileSync(OUT, sql, 'utf8');

console.log(`wrote ${OUT}`);
console.log(`units:   ${unitRows.length} (${unitRows.filter((u) => u.kind === 'department').length} departments, ${unitRows.filter((u) => u.kind === 'office').length} offices)`);
console.log(`people:  ${PEOPLE.length}`);
console.log(`roles:   ${roleValues.length}`);
